from random import randint

from box import box

def generate():
    fields = list()
    field = list()
    field.append(box((0, 0), [True, False, False, True]))
    field.append(box((0, 1), [True, False, False, False]))
    field.append(box((0, 2), [True, False, False, False]))
    field.append(box((0, 3), [True, False, False, False]))
    field.append(box((0, 4), [True, False, False, False]))
    field.append(box((0, 5), [True, True, False, False]))
    field.append(box((1, 0), [False, False, False, True]))
    field.append(box((1, 1), [False, False, False, False]))
    field.append(box((1, 2), [False, False, False, False]))
    field.append(box((1, 3), [False, False, False, False]))
    field.append(box((1, 4), [False, False, False, False]))
    field.append(box((1, 5), [False, True, True, False]))
    field.append(box((2, 0), [False, False, False, True]))
    field.append(box((2, 1), [False, False, False, False]))
    field.append(box((2, 2), [False, False, False, False]))
    field.append(box((2, 3), [False, False, False, False]))
    field.append(box((2, 4), [False, True, False, False]))
    field.append(box((3, 0), [False, False, True, True]))
    field.append(box((3, 1), [False, False, True, False]))
    field.append(box((3, 2), [False, False, False, False]))
    field.append(box((3, 3), [False, False, False, False]))
    field.append(box((3, 4), [False, True, False, False]))
    field.append(box((4, 2), [False, False, False, True]))
    field.append(box((4, 3), [False, False, False, False]))
    field.append(box((4, 4), [False, False, False, False]))
    field.append(box((4, 5), [True, True, False, False]))
    field.append(box((5, 2), [False, False, True, True]))
    field.append(box((5, 3), [False, False, True, False]))
    field.append(box((5, 4), [False, False, True, False]))
    field.append(box((5, 5), [False, True, True, False]))
    fields.append(field)
    field = list()
    field.append(box((0, 1), [True, False, False, True]))
    field.append(box((0, 2), [True, False, False, False]))
    field.append(box((0, 3), [True, True, False, False]))
    field.append(box((1, 1), [False, False, False, True]))
    field.append(box((1, 2), [False, False, False, False]))
    field.append(box((1, 3), [False, False, False, False]))
    field.append(box((1, 4), [True, False, False, False]))
    field.append(box((1, 5), [True, True, False, False]))
    field.append(box((2, 0), [True, False, False, True]))
    field.append(box((2, 1), [False, False, False, False]))
    field.append(box((2, 2), [False, False, False, False]))
    field.append(box((2, 3), [False, False, False, False]))
    field.append(box((2, 4), [False, False, False, False]))
    field.append(box((2, 5), [False, True, True, False]))
    field.append(box((3, 0), [False, False, False, True]))
    field.append(box((3, 1), [False, False, False, False]))
    field.append(box((3, 2), [False, False, False, False]))
    field.append(box((3, 3), [False, False, False, False]))
    field.append(box((3, 4), [False, True, True, False]))
    field.append(box((4, 0), [False, False, True, True]))
    field.append(box((4, 1), [False, False, True, False]))
    field.append(box((4, 2), [False, False, False, False]))
    field.append(box((4, 3), [False, True, False, False]))
    field.append(box((5, 2), [False, False, False, True]))
    field.append(box((5, 3), [False, False, False, False]))
    field.append(box((5, 4), [True, False, False, False]))
    field.append(box((5, 5), [True, True, False, False]))
    field.append(box((6, 2), [False, False, True, True]))
    field.append(box((6, 3), [False, False, True, False]))
    field.append(box((6, 4), [False, False, True, False]))
    field.append(box((6, 5), [False, True, True, False]))
    fields.append(field)
    field = list()
    field.append(box((0, 2), [True, False, False, True]))
    field.append(box((0, 3), [True, True, False, False]))
    field.append(box((1, 2), [False, False, False, True]))
    field.append(box((1, 3), [False, False, False, False]))
    field.append(box((1, 4), [True, True, False, False]))
    field.append(box((2, 0), [True, False, False, True]))
    field.append(box((2, 1), [True, False, False, False]))
    field.append(box((2, 2), [False, False, False, False]))
    field.append(box((2, 3), [False, False, False, False]))
    field.append(box((2, 4), [False, False, False, False]))
    field.append(box((2, 5), [True, True, False, False]))
    field.append(box((3, 0), [False, False, False, True]))
    field.append(box((3, 1), [False, False, False, False]))
    field.append(box((3, 2), [False, False, False, False]))
    field.append(box((3, 3), [False, False, True, False]))
    field.append(box((3, 4), [False, False, True, False]))
    field.append(box((3, 5), [False, True, False, False]))
    field.append(box((4, 0), [False, False, False, True]))
    field.append(box((4, 1), [False, False, False, False]))
    field.append(box((4, 2), [False, True, False, False]))
    field.append(box((4, 5), [False, True, False, True]))
    field.append(box((5, 0), [False, False, True, True]))
    field.append(box((5, 1), [False, False, False, False]))
    field.append(box((5, 2), [False, True, False, False]))
    field.append(box((5, 4), [True, False, False, True]))
    field.append(box((5, 5), [False, True, False, False]))
    field.append(box((6, 1), [False, False, True, True]))
    field.append(box((6, 2), [False, True, True, False]))
    field.append(box((6, 4), [False, False, True, True]))
    field.append(box((6, 5), [False, True, True, False]))
    fields.append(field)
    return fields[randint(0, len(fields)-1)]